### PR TITLE
Set up a 'Hello world' project with two apps

### PR DESCRIPTION
**Pull request by TaiwoEnoch**
## Project requirements

- [ ] Create a new Rails API app called 'hello-rails-back-end'.
- [ ] Initialize your project with Git.
- [ ] Make sure that your project has a Postgres database set up.
- [ ] Create a table for storing your messages and create 5 different greetings.
- [ ] Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and rails route).
- [ ]  Create a new React app called 'hello-react-front-end'
- [ ] Initialize your project with Git.
- [ ] Create the App component with react-router.
- [ ] Create the Greeting component that will display a greeting. Set it up as a route in your App component.
- [ ] Create a store, an action and a reducer that will connect to you API endpont to get the random greeting.
- [ ] Display the random greeting in your Greeting component.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @TaiwoEnoch 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow proper Gitflow

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by TaiwoEnoch** [comment]
Hi @prolajumokeoni can you please, let me know the actual problem with the PR, Is it because the linters are not yet run, or what exactly, I need your help for enlightenment.

**Comment by shella12** [comment]
> Hi @prolajumokeoni can you please, let me know the actual problem with the PR, Is it because the linters are not yet run, or what exactly, I need your help for enlightenment.

Hi @TaiwoEnoch the problem stated by the previous reviewer is that you are not following the correct `gitflow` meaning you need to send a PR from feature branch to `dev` instead of `dev` to `main`. I'm going to mark your Pr invalid Kindly fix your `gitflow` in order for us to proceed with your request.

**Review by shella12 — COMMENTED** [review]
Hi @TaiwoEnoch, 

#  Status: Invalidated :red_circle: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have correct `gitflow`. As stated by the previous reviewer you need to send a PR from feature branch to dev instead of dev to main. I'm going to mark your PR invalid. Kindly fix your `gitflow` in order for us to proceed with your request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by TaiwoEnoch** [comment]
Hi, @prolajumokeoni  @shella12  I am always having a lot of issues when it comes to this because mostly I will submit a project vividly from the feature branch to the dev and a code reviewer will still have the audacity to tell me to create a final request from the dev to make, I am frustrated right now 😞 

I will make the correction right now

@shella12 Thank you for the clarity

**Pull request closed without merging**
